services:
  - type: redis
    name: industrial-nexus-redis
    ipAllowList: []

  - type: web
    name: industrial-nexus-api
    env: node
    buildCommand: npm install && cd apps/backend && npm install && npx prisma generate && npx prisma migrate deploy && npm run build
    startCommand: cd apps/backend && node dist/src/main
    envVars:
      - key: RENDER_DATABASE_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: REDIS_ENABLED
        value: "true"
      - key: REDIS_URL
        fromService:
          type: redis
          name: industrial-nexus-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://www.industrialnexus.com.ng,https://industrial-nexus-app.onrender.com
      - key: AWS_REGION
        sync: false
      - key: AWS_S3_BUCKET
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: APP_URL
        value: https://www.industrialnexus.com.ng
      - key: MAPBOX_TOKEN
        sync: false

  - type: web
    name: industrial-nexus-app
    env: node
    buildCommand: npm install && cd apps/frontend && npm install && rm -rf .next && npm run build
    startCommand: cd apps/frontend && npm run start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://industrial-nexus-api.onrender.com
      - key: NEXT_PUBLIC_WS_URL
        value: https://industrial-nexus-api.onrender.com
      - key: NEXT_IGNORE_INCORRECT_LOCKFILE
        value: "true"
      - key: NEXT_PUBLIC_MAPBOX_TOKEN
        sync: false
      - key: NEXT_PUBLIC_MAP_TILE_STYLE_URL
        value: "mapbox://styles/mapbox/streets-v12"
